file= open("file handling.txt")
print(file.readline(),end="")
print(file.readline(),end="")
print(file.readline(),end="")
print(file.readline(),end="")
file=open("file handling.txt")
line=file.readline()
print(line)
print(len(line))